// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDievDhUxuEq3bHAOp44ENnQP3ttIMLE8M',
    appId: '1:525877930158:web:c4eb8099e16f3027abe53f',
    messagingSenderId: '525877930158',
    projectId: 'doan-86f54',
    authDomain: 'doan-86f54.firebaseapp.com',
    databaseURL: 'https://doan-86f54-default-rtdb.firebaseio.com',
    storageBucket: 'doan-86f54.firebasestorage.app',
    measurementId: 'G-BDVRV2DZ1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN5Tt74sVkB2qGa-Pw1Rl_iS6o1lQ9RDg',
    appId: '1:525877930158:android:b27c3f107c5d9348abe53f',
    messagingSenderId: '525877930158',
    projectId: 'doan-86f54',
    databaseURL: 'https://doan-86f54-default-rtdb.firebaseio.com',
    storageBucket: 'doan-86f54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaqNkPG5725TRSK2X1NyDJ5xu50GBl_k4',
    appId: '1:525877930158:ios:bb968b678263f058abe53f',
    messagingSenderId: '525877930158',
    projectId: 'doan-86f54',
    databaseURL: 'https://doan-86f54-default-rtdb.firebaseio.com',
    storageBucket: 'doan-86f54.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaqNkPG5725TRSK2X1NyDJ5xu50GBl_k4',
    appId: '1:525877930158:ios:bb968b678263f058abe53f',
    messagingSenderId: '525877930158',
    projectId: 'doan-86f54',
    databaseURL: 'https://doan-86f54-default-rtdb.firebaseio.com',
    storageBucket: 'doan-86f54.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDievDhUxuEq3bHAOp44ENnQP3ttIMLE8M',
    appId: '1:525877930158:web:7894ecfcf6f17cf6abe53f',
    messagingSenderId: '525877930158',
    projectId: 'doan-86f54',
    authDomain: 'doan-86f54.firebaseapp.com',
    databaseURL: 'https://doan-86f54-default-rtdb.firebaseio.com',
    storageBucket: 'doan-86f54.firebasestorage.app',
    measurementId: 'G-9DX1YJWTQ6',
  );
}
